# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Rsvp.create(names: "Uncle Brian & Dora", max_guests: 2, code: 'uQk6')
Rsvp.create(names: "Auntie sue & david & carer", max_guests: 3, code: 'bE7r')
Rsvp.create(names: "Roger & Margret", max_guests: 2, code: '8Akm')
Rsvp.create(names: "Auntie Nancy & guest", max_guests: 2, code: 'Z3fp')
Rsvp.create(names: "Bill & Kath", max_guests: 2, code: 'fG9s')
Rsvp.create(names: "Peter & Julie & Olivia", max_guests: 3, code: '58FG')
Rsvp.create(names: "Paul & Donna  & Jack", max_guests: 3, code: 'K4vt')
Rsvp.create(names: "Sam & Max & other", max_guests: 3, code: 'cjUd')
Rsvp.create(names: "Chris & Joe", max_guests: 2, code: 'a4Qg')
Rsvp.create(names: "Alan & Sheila", max_guests: 2, code: 'aq8g')
Rsvp.create(names: "Amber", max_guests: 2, code: 'WtEm')
Rsvp.create(names: "Moira", max_guests: 1, code: 'R6Kk')
Rsvp.create(names: "Katrin & Simon & Harry", max_guests: 3, code: 'bRWZ')
Rsvp.create(names: "Don & family", max_guests: 2, code: 'DNYn')
Rsvp.create(names: "Tony & Barbra", max_guests: 2, code: 'sG3g')
Rsvp.create(names: "Mike & Isabell", max_guests: 2, code: 'Z2Dh')
Rsvp.create(names: "Peter & family", max_guests: 2, code: 'H5zy')
Rsvp.create(names: "Chris & Rebecca", max_guests: 2, code: 'C6eE')
Rsvp.create(names: "Vikki & Andrew", max_guests: 2, code: 'b8Br')
Rsvp.create(names: "Trevor & Liz", max_guests: 2, code: 'qY2t')
Rsvp.create(names: "Ian & Charlie", max_guests: 2, code: 'HhV4')
Rsvp.create(names: "Dawn & guest", max_guests: 2, code: 'AqH6')
Rsvp.create(names: "Uncle Hung", max_guests: 2, code: '97sA')
Rsvp.create(names: "Julia & Ben", max_guests: 2, code: '4Cga')
Rsvp.create(names: "Alan & Metok", max_guests: 2, code: '8XPw')
Rsvp.create(names: "Pauline & guest", max_guests: 2, code: 'Pv8q')
Rsvp.create(names: "Sui & Dave", max_guests: 2, code: 'w4FU')
Rsvp.create(names: "Andy & Pauline", max_guests: 4, code: 'E6Yu')
Rsvp.create(names: "Hon & Megan", max_guests: 4, code: 'qAfe')
Rsvp.create(names: "Rob & Pol", max_guests: 2, code: 'vESe')
Rsvp.create(names: "Dave & Karen & Oliver", max_guests: 3, code: 'Tmqw')
Rsvp.create(names: "Sarah & guest", max_guests: 2, code: '6r4V')
Rsvp.create(names: "George & jane & Jason & Andrew", max_guests: 4, code: 'dcN8')
Rsvp.create(names: "Steve & Louise", max_guests: 2, code: '6Yhr')
Rsvp.create(names: "Andy & Claire & 2", max_guests: 4, code: 'z7iM')
Rsvp.create(names: "Phil & family", max_guests: 3, code: '8yZN')
Rsvp.create(names: "Dougy & Guest", max_guests: 2, code: 'Wgb3')
Rsvp.create(names: "Tom & Emma", max_guests: 2, code: '25ta')
Rsvp.create(names: "Martin & Cat", max_guests: 2, code: 'XF7a')
Rsvp.create(names: "Adam & Dawn", max_guests: 2, code: 'vpQ5')
Rsvp.create(names: "Andrew& Nina & 1", max_guests: 3, code: 'KZs8')
Rsvp.create(names: "Nix & Brian", max_guests: 2, code: 'LVaL')
Rsvp.create(names: "Steve", max_guests: 1, code: 'nSkD')
Rsvp.create(names: "Katie", max_guests: 1, code: '9Pqf')
Rsvp.create(names: "Gary & Ria", max_guests: 2, code: '5BYu')
Rsvp.create(names: "Olya & guest", max_guests: 2, code: 'n6JE')
Rsvp.create(names: "Kayan & Mike", max_guests: 4, code: 'V5RY')
Rsvp.create(names: "Carmen & Andy", max_guests: 2, code: 'nzzc')
Rsvp.create(names: "Shanshan & Chris", max_guests: 2, code: 'EJLz')
Rsvp.create(names: "Connie & Andrew", max_guests: 4, code: '2QvP')
Rsvp.create(names: "Fay & Michael", max_guests: 2, code: 'cYXS')
Rsvp.create(names: "Angela & Guest", max_guests: 2, code: 'B6Ya')
Rsvp.create(names: "Ellen & Guest", max_guests: 2, code: 'LmWb')
Rsvp.create(names: "James & Natalie", max_guests: 2, code: 'SBa7')
Rsvp.create(names: "Daniel & Candy", max_guests: 2, code: 'xGLV')
Rsvp.create(names: "Matthew & family", max_guests: 3, code: 'UjXZ')
Rsvp.create(names: "Martin & family", max_guests: 5, code: 'pnZX')
Rsvp.create(names: "Sarah & Chris", max_guests: 4, code: '5xHK')
Rsvp.create(names: "Paul & Emily", max_guests: 2, code: 'HQXJ')
Rsvp.create(names: "Jim & Sal", max_guests: 3, code: 'QBXs')
Rsvp.create(names: "Sam & Lorrie", max_guests: 4, code: 'DFQ3')
Rsvp.create(names: "Patrick & Guest", max_guests: 2, code: 'YxNx')
Rsvp.create(names: "Darryl & Guest", max_guests: 2, code: 'qtRX')
Rsvp.create(names: "Phil & Rebecca", max_guests: 2, code: 'L8nn')
Rsvp.create(names: "Piotr", max_guests: 1, code: '5xRw')
Rsvp.create(names: "Kobby & Sara", max_guests: 2, code: 'q8Uv')
Rsvp.create(names: "Dan", max_guests: 1, code: 'vgVQ')
Rsvp.create(names: "Kenzie", max_guests: 2, code: 'PjBA')
Rsvp.create(names: "Gary & family", max_guests: 3, code: 'Wn4T')
Rsvp.create(names: "Radka & Brian", max_guests: 2, code: 'a2pK')
Rsvp.create(names: "Sai & Jenny", max_guests: 3, code: 'P5zV')
Rsvp.create(names: "James & guest", max_guests: 2, code: 'Qx6J')
Rsvp.create(names: "Steven & guest", max_guests: 2, code: 'ir9t')
Rsvp.create(names: "Wei Lin & ah Bee", max_guests: 3, code: 'zXy9')
Rsvp.create(names: "Eric & Karen", max_guests: 3, code: 'U5st')
Rsvp.create(names: "Alfred & Sophie", max_guests: 3, code: 'p4W9')
Rsvp.create(names: "Cola & guest", max_guests: 2, code: '6Jm4')